stages:
  - build
  - test
  - deploy

variables:
  AWS_REGION: "us-west-2"
  AWS_INSTANCE_ID: "i-0196a58982f566048"
  AWS_INSTANCE_IP: "35.85.30.54"
  AWS_INSTANCE_SSH_KEY: "~/.ssh/id_rsa"

before_script:
  - apt-get update -qy
  - apt-get install -y python3-pip
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install awscli

build-job:
  stage: build
  script:
    - echo "Building the application..."
    - echo "Build complete."

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Unit tests passed."

lint-test-job:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application to AWS EC2..."
    - echo "Copying artifacts to EC2 instance..."
    - aws s3 sync savannah-web-page/ s3://storage-2-brian/savannah-web-page/
    - echo "Starting EC2 instance..."
    - aws ec2 start-instances --instance-ids $AWS_INSTANCE_ID
    - echo "Deploy complete."
  only:
    - master
